variables:
  LAMP_GROUP_MAXIMUM:
    default: 1
    description: Minimum number of instances the autoscale group will launch
    overrides:
    required: true
    type: number
  LAMP_GROUP_MINIMUM:
    default: 1
    description: Maximum number of instances the autoscale group will launch
    overrides:
    required: true
    type: number
  LAMP_INGRESS_CIDRS:
    default: 
        - 0.0.0.0/0
    description: null
    overrides: null
    required: true
    type: arra
  LAMP_INGRESS_CIDR_PORTS:
    default:
       - 8080
       - 80
       - 443
       - 22
    description:
    overrides:
    required: true
    type: array
  LAMP_INGRESS_GROUP_PORTS:
    default:
       - 8080
       - 80
       - 443
    description:
    overrides:
    required: true
    type: array
  LAMP_KEYPAIR:
    default:
    description:
    overrides:
    required: true
    type:
  LAMP_NAME:
    default: LAMP
    description:
    overrides:
    required: true
    type:
  LAMP_SIZE:
<<<<<<< HEAD
    default: t2.micro
    description:
    overrides:
    required: true
    type:
  VPC_NAME:
    default: test-vpc
=======
    default: t2.small
    description: the size of the server to launch
    required: true
  LAMP_KEYPAIR:
    description: the name of the keypair to launch jenkins with
    required: true
  PRIVATE_SUBNET_NAME:
    default: test-public-subnet
    description: The name of the public subnet you want to create your server in
    overrides: null
    required: true
    type: string
  REGION:
    default:
>>>>>>> f08daef46c86c0607cb4591791a808963b94fc11
    description:
    overrides:
    required: true
    type: string
  YUM_REPO_BUCKET:
    default:
    description:
    overrides:
    required: false
    type:
<<<<<<< HEAD
  VPC_CIDR:
    default: 10.11.0.0/16
=======
  ENV:
    default: dev
    description: just a way to namespace the backups
    required: true
  VPC_CIDR: 
    default: 10.0.0.0/16
>>>>>>> f08daef46c86c0607cb4591791a808963b94fc11
    description: The CIDR to match to locate the VPC that this server is to be created in
    overrides: null
    required: true
    type: string
  PUBLIC_ROUTE_NAME:
    default: test-public-route
    description: null
    overrides: null
    required: true
<<<<<<< HEAD
    type: string
  PUBLIC_SUBNET_NAME:
    default: test-public-subnet
    description: The name of the public subnet you want to create your server in
    overrides: null
    required: true
=======
>>>>>>> f08daef46c86c0607cb4591791a808963b94fc11
    type: string